apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: est-app 
  name: estetica-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: estetica-app
  template:
    metadata:
      labels:
        app: estetica-app
    spec:
      containers:
        - name: estetica-app
          image: faelsouz/dra-ana-paula:v1
          ports:
            - containerPort: 80
          env:
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: url
            - name: VITE_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: anon-key
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15 # Aumenta o delay inicial
            periodSeconds: 20 # Aumenta a periodicidade
            timeoutSeconds: 5 # Timeout maior para garantir que a aplicação tenha tempo para responder
            failureThreshold: 3 # Aumenta o número de falhas permitidas antes de reiniciar o contêiner
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10 # Dê mais tempo para a aplicação inicializar
            periodSeconds: 10 # Aumenta a periodicidade
            timeoutSeconds: 5 # Timeout para a aplicação responder
            failureThreshold: 3 # Mais tolerância a falhas antes de considerar a aplicação não pronta
#        - name: nginx-prometheus-exporter
#          image: nginx/nginx-prometheus-exporter:0.10.0
#          args:
#            - "-nginx.scrape-uri=http://localhost:80/nginx_status"
#          ports:
#            - containerPort: 9113
#          volumeMounts:
#            - name: nginx-config
#              mountPath: /etc/nginx/nginx.conf
#              subPath: nginx.conf
#      volumes:
#        - name: nginx-config
#          configMap:
#            name: nginx-config
