apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: est-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Define o espaço necessário
