apiVersion: v1
kind: Service
metadata:
  name: estetica-app-service
  namespace: est-app
  labels:
    app: estetica-app
spec:
  selector:
    app: estetica-app
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP