apiVersion: v1
kind: Service
metadata:
  name: estetica-metrics
  labels:
    app: estetica-app
spec:
  selector:
    app: estetica-app
  ports:
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
