name: CI/CD Pipeline

on:
  push:
    branches: [feature-0001]
  pull_request:
    branches: [feature-0001]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: echo "Skip test step for now"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: docker build -t faelsouz/dra-ana-paula:v2.0.0 .
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
  
      - name: Build Docker image
        run: docker build -t faelsouz/dra-ana-paula:v1 .
  
      - name: Load image into Minikube
        run: minikube image load faelsouz/dra-ana-paula:v1 --profile=devops-dev
  
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/
  
      - name: Esperar app responder
        run: |
          APP_URL="http://$(minikube ip):30080"
          echo "Esperando a aplicação ficar disponível em $APP_URL..."
          for i in {1..10}; do
            if curl -s $APP_URL > /dev/null; then
              echo "Aplicação está online!"
              exit 0
            else
              echo "Tentando novamente..."
              sleep 5
            fi
          done
          echo "Aplicação não respondeu!"
          exit 1
